web/router.ex
defmodule PushApiServer.Router do
  use PushApiServer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PushApiServer do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index, as: :root

    get "/signup", RegistrationController, :new, as: :signup
    get "/signin", SessionController, :new, as: :signin
    delete "/signout", SessionController, :delete, as: :signout

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/passwords", PasswordController
    resources "/sessions", SessionController

    resources "/users", UserController
    resources "/projects", ProjectController
    resources "/pushes", PushController, only: [:index, :show, :delete]

    resources "/projects", ProjectController
  end

  # Other scopes may use custom stacks.
  scope "/api", PushApiServer do
    pipe_through :api
    resources "/pushes", API.PushController
  end
end

web/views/layout_view.ex
defmodule PushApiServer.LayoutView do
  use PushApiServer.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PushApiServer!</title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://www.gstatic.com/firebasejs/3.6.3/firebase.js"></script>
    <script>
      // Initialize Firebase
      var config = {
        apiKey: "AIzaSyAqlKB-3fbraWsfvxJMMx6QCPaoPJeSlhQ",
        authDomain: "test-e5174.firebaseapp.com",
        databaseURL: "https://test-e5174.firebaseio.com",
        storageBucket: "test-e5174.appspot.com",
        messagingSenderId: "311975232187"
      };
      firebase.initializeApp(config);
    </script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <li><%= link "Signout", to: signout_path(@conn, :delete), method: "DELETE" %></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>